### ISSUE TITLE
how to authenticate

### ISSUE THREAD

**Issue by alextes** [andrioid/gh-action-k8s-set-image#2]
every real k8s cluster will be guarded by some form of authentication.

is this action intending to support them or is it only for unauthenticated clusters? In case of the former, could we add something to the readme describing how to go about it? (:

**Comment by andrioid** [comment]
It’s just a wrapper for kubectl. I use gcloud and configure the cluster before using this action. I’ll try to add an example to the README. So, I’ll leave the issue open.

**Comment by alextes** [comment]
hé @andrioid quick response!! I switched over to https://github.com/steebchen/kubectl already. It uses a secret plus base64 encoding to pass the config. I don't want to cause you unnecessary work so thought I'd let you know. But maybe more people will show up to this issue asking for it! so feel free to leave open / close (:

**Comment by andrioid** [comment]
Kubectl is stated as a [requirement](https://github.com/andrioid/gh-action-k8s-set-image#requirements) for the action. Maybe I should make it a little clearer. The only thing this action does is to reduce clutter when you need to change a bunch of deployments from a Github workflow.

I'm glad you found a solution that works for you.

If anyone else stumbles upon this issue, this is how it looks where I use it:

```
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ env.GCP_PROJECT_ID }}
                  service_account_key: ${{ secrets.GCP_CREDENTIALS }}
                  export_default_credentials: true
```
I also realized that I don't actually use this myself anymore. So, I'm archiving the repo.
